"""Canonical pywebview js_api method names (mirror web/src/contracts/bridgeParity.ts)."""

from __future__ import annotations

PYWEBVIEW_API_METHODS: tuple[str, ...] = (
    "get_app_info",
    "get_snapshot",
    "select_folder",
    "start_scan",
    "cancel_run",
    "set_work_mode",
    "query_review_rows",
    "query_file_rows",
    "query_quality_rows",
    "get_duplicate_group_detail",
    "get_quality_issue_detail",
    "get_quality_repair_preview",
    "apply_quality_repair",
    "discard_quality_repair_preview",
    "get_move_preview",
    "apply_resolved_actions",
    "discard_move_preview",
    "update_review_decisions",
    "summarize_auto_select_keepers",
    "summarize_resolve_auto_approve",
    "start_resolve_auto_approve_job",
    "cancel_resolve_auto_approve_job",
    "get_app_setting",
    "set_app_setting",
    "query_log_entries",
    "get_logs_artifacts",
    "get_finalize_summary",
    "preview_finalize_cleanup",
    "run_finalize_verification",
    "get_finalize_report",
    "cancel_finalize",
)
