"""Release diagnostics metadata (PR-24). Not used for feature gating."""

from __future__ import annotations

import importlib.util
import platform
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Literal

from app.runtime_paths import bundle_root, is_frozen

APP_NAME = "NovelGuard"
APP_VERSION = "0.24.0"
BUILD_TYPE: Literal["dev", "production", "packaged"] = "dev"
GIT_COMMIT: str | None = None
BUILT_AT: str | None = None
FRONTEND_BUILD = "web/build"

_STAMP_PATH = Path(__file__).with_name("_build_stamp.py")


def _load_build_stamp_file() -> None:
    """Apply generated stamp when present (written by package_windows.py)."""
    global GIT_COMMIT, BUILT_AT, BUILD_TYPE
    candidates = [_STAMP_PATH]
    if is_frozen():
        candidates.insert(0, bundle_root() / "app" / "_build_stamp.py")
    for path in candidates:
        if not path.is_file():
            continue
        spec = importlib.util.spec_from_file_location("_ng_build_stamp", path)
        if spec is None or spec.loader is None:
            continue
        stamp = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(stamp)
        GIT_COMMIT = stamp.GIT_COMMIT
        BUILT_AT = stamp.BUILT_AT
        BUILD_TYPE = stamp.BUILD_TYPE
        return


def _write_build_stamp_file() -> None:
    content = (
        '"""Auto-generated by packaging. Do not commit."""\n'
        "from __future__ import annotations\n"
        "\n"
        "from typing import Literal\n"
        "\n"
        f"GIT_COMMIT: str | None = {GIT_COMMIT!r}\n"
        f"BUILT_AT: str | None = {BUILT_AT!r}\n"
        f'BUILD_TYPE: Literal["dev", "production", "packaged"] = {BUILD_TYPE!r}\n'
    )
    _STAMP_PATH.write_text(content, encoding="utf-8")


_load_build_stamp_file()


@dataclass(frozen=True)
class AppInfo:
    appName: str
    version: str
    buildType: str
    gitCommit: str | None
    builtAt: str | None
    frontendBuild: str
    pythonRuntime: str


def resolve_build_type() -> Literal["dev", "production", "packaged"]:
    if is_frozen():
        return "packaged"
    return BUILD_TYPE


def apply_build_stamp(
    *,
    git_commit: str | None = None,
    built_at: str | None = None,
    build_type: Literal["dev", "production", "packaged"] | None = None,
) -> None:
    """Write stamp module for PyInstaller; update in-process globals."""
    global GIT_COMMIT, BUILT_AT, BUILD_TYPE
    if git_commit is not None:
        GIT_COMMIT = git_commit
    if built_at is not None:
        BUILT_AT = built_at
    if build_type is not None:
        BUILD_TYPE = build_type
    if build_type == "packaged":
        _write_build_stamp_file()


def get_app_info() -> dict[str, object]:
    return asdict(
        AppInfo(
            appName=APP_NAME,
            version=APP_VERSION,
            buildType=resolve_build_type(),
            gitCommit=GIT_COMMIT,
            builtAt=BUILT_AT,
            frontendBuild=FRONTEND_BUILD,
            pythonRuntime=platform.python_version(),
        )
    )
