#!/usr/bin/env python3
"""Generate gui.styles.tokens from root DESIGN.md."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
DESIGN_PATH = REPO_ROOT / "DESIGN.md"
OUT_DIR = REPO_ROOT / "src" / "gui" / "styles" / "tokens"

# DESIGN token key -> Python constant name (legacy + semantic aliases)
DARK_ALIASES: dict[str, list[str]] = {
    "background": ["BACKGROUND", "BG_BODY"],
    "surface": ["SURFACE", "BG_CONTAINER", "BG_SIDEBAR", "BG_CARD", "BG_INPUT"],
    "surface-elevated": ["SURFACE_ELEVATED"],
    "on-surface": ["ON_SURFACE", "TEXT_PRIMARY"],
    "on-surface-variant": ["ON_SURFACE_VARIANT", "TEXT_SECONDARY"],
    "muted": ["MUTED", "TEXT_TERTIARY", "TEXT_DISABLED"],
    "primary": ["PRIMARY", "PRIMARY_START", "PRIMARY_END", "BORDER_ACCENT"],
    "secondary": ["SECONDARY"],
    "selection": ["SELECTION"],
    "outline": ["OUTLINE", "BORDER_PRIMARY"],
    "hover": ["HOVER", "BORDER_SECONDARY"],
    "error": ["ERROR", "COLOR_DANGER"],
    "success": ["SUCCESS", "COLOR_SUCCESS"],
    "status-duplicate-fg": ["TYPE_DUPLICATE_FG"],
    "status-duplicate-bg": ["TYPE_DUPLICATE_BG"],
    "status-small-fg": ["TYPE_SMALL_FG"],
    "status-small-bg": ["TYPE_SMALL_BG"],
    "status-encoding-fg": ["TYPE_ENCODING_FG"],
    "status-encoding-bg": ["TYPE_ENCODING_BG"],
    "status-integrity-fg": ["TYPE_INTEGRITY_FG"],
    "status-integrity-bg": ["TYPE_INTEGRITY_BG"],
}

LIGHT_PREFIX = "LIGHT_"


def _parse_front_matter(text: str) -> dict:
    match = re.match(r"^---\s*\n(.*?)\n---", text, re.DOTALL)
    if not match:
        raise ValueError("DESIGN.md: missing YAML front matter")
    return yaml.safe_load(match.group(1)) or {}


def _emit_dark_module(module_doc: str, const_map: dict[str, str]) -> str:
    lines = [
        f'"""{module_doc}"""',
        "",
        "# GENERATED by scripts/sync_design_tokens.py — do not edit by hand.",
        "from typing import Final",
        "",
    ]
    emitted: set[str] = set()
    for key, names in DARK_ALIASES.items():
        if key not in const_map:
            continue
        value = const_map[key]
        for name in names:
            if name in emitted:
                continue
            lines.append(f"{name}: Final[str] = {value!r}")
            emitted.add(name)
    if "COLOR_WARNING" not in emitted:
        lines.append('COLOR_WARNING: Final[str] = "#F59E0B"')
    lines.append("")
    return "\n".join(lines)


def _emit_light_module(light_colors: dict[str, str]) -> str:
    """Emit light tokens with the same constant names as dark for theme_registry."""
    lines = [
        '"""Light theme color tokens from DESIGN.md colors-light."""',
        "",
        "# GENERATED by scripts/sync_design_tokens.py — do not edit by hand.",
        "from typing import Final",
        "",
    ]
    emitted: set[str] = set()
    for key, names in DARK_ALIASES.items():
        if key not in light_colors:
            continue
        value = light_colors[key]
        for name in names:
            if name in emitted:
                continue
            lines.append(f"{name}: Final[str] = {value!r}")
            emitted.add(name)
    if "COLOR_WARNING" not in emitted:
        lines.append('COLOR_WARNING: Final[str] = "#F59E0B"')
    lines.append("")
    return "\n".join(lines)


def build_tokens(data: dict) -> tuple[dict[str, str], dict[str, str]]:
    colors = data.get("colors") or {}
    light = data.get("colors-light") or {}
    if not colors:
        raise ValueError("DESIGN.md: colors map is required")
    return colors, light


def write_tokens(check_only: bool) -> int:
    raw = DESIGN_PATH.read_text(encoding="utf-8")
    data = _parse_front_matter(raw)
    colors, light = build_tokens(data)

    dark_body = _emit_dark_module("Dark theme color tokens from DESIGN.md.", colors)
    light_body = _emit_light_module(light)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "__init__.py").write_text(
        '"""Design tokens generated from DESIGN.md."""\n',
        encoding="utf-8",
    )

    targets = {
        OUT_DIR / "colors_dark.py": dark_body,
        OUT_DIR / "colors_light.py": light_body,
    }

    if check_only:
        for path, body in targets.items():
            if not path.exists() or path.read_text(encoding="utf-8") != body:
                print(f"stale: {path.relative_to(REPO_ROOT)}", file=sys.stderr)
                return 1
        print("design tokens up to date")
        return 0

    for path, body in targets.items():
        path.write_text(body, encoding="utf-8")
        print(f"wrote {path.relative_to(REPO_ROOT)}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if generated files are out of date",
    )
    args = parser.parse_args()
    if not DESIGN_PATH.is_file():
        print(f"missing {DESIGN_PATH}", file=sys.stderr)
        return 1
    return write_tokens(check_only=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
